name: main

permissions: write-all

on: [pull_request, push]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.0'
          channel: 'stable'

      - name: Clean Dependencies
        run: flutter clean

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format --set-exit-if-changed lib test

      - name: Analyze
        run: flutter analyze lib test

      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

  prerelease:
    runs-on: ubuntu-latest
    needs:
      - lint-test
#    if: github.ref == 'refs/heads/main' todo! will reenable

    steps:
      - uses: actions/checkout@v4

      - name: Run Release
        uses: google-github-actions/release-please-action@v4
        with:
          target-branch: main
          token: ${{ secrets.GIT_TOKEN }}
          config-file: release-please-config.json
#          manifest-file: .release-please-manifest.json

